/*
 * Copyright 2008 Ayman Al-Sairafi ayman.alsairafi@gmail.com
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. 
 * You may obtain a copy of the License 
 *       at http://www.apache.org/licenses/LICENSE-2.0 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 * See the License for the specific language governing permissions and 
 * limitations under the License.  
 */
package com.echeloneditor.main;

import java.awt.HeadlessException;
import java.util.regex.PatternSyntaxException;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.LayoutStyle;
import javax.swing.SwingUtilities;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.text.JTextComponent;

import com.echeloneditor.listeners.EscapeListener;

/**
 * A Find and Replace Dialog. The dialog will also act as a listener to Document changes so that all highlights are updated if the document is changed.
 * 
 * @author Ayman Al-Sairafi
 */
public class FindAndReplaceDialog extends JDialog implements CaretListener, EscapeListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private JTextComponent textComponent;

	private JButton jBtnNext;
	private JButton jBtnPrev;
	private JButton jBtnReplace;
	private JButton jBtnReplaceAll;
	private JCheckBox jChkIgnoreCase;
	private JCheckBox jChkRegex;
	private JCheckBox jChkWrap;
	private JComboBox jCmbFind;
	private JComboBox jCmbReplace;
	private JLabel jLblFind;
	private JLabel jLblReplace;
	private JToggleButton jTglHighlight;

	// End of variables declaration//GEN-END:variables

	/**
	 * Creates new form FindDialog
	 * 
	 * @param text
	 * @param dsd
	 *            DocumentSerachData
	 */
	public FindAndReplaceDialog(JTextComponent text) {
		super((JFrame) SwingUtilities.getRoot(text));
		initComponents();
		//textComponent.addCaretListener(this);
		setLocationRelativeTo(text.getRootPane());
		getRootPane().setDefaultButton(jBtnNext);
		// SwingUtils.addEscapeListener(this);
		jBtnReplaceAll.setEnabled(text.isEditable() && text.isEnabled());
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		jLblFind = new JLabel();
		jBtnNext = new JButton();
		jBtnPrev = new JButton();
		jBtnReplaceAll = new JButton();
		jChkWrap = new JCheckBox();
		jChkRegex = new JCheckBox();
		jChkIgnoreCase = new JCheckBox();
		jLblReplace = new JLabel();
		jTglHighlight = new JToggleButton();
		jCmbReplace = new JComboBox();
		jCmbFind = new JComboBox();
		jBtnReplace = new JButton();

		java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
		setTitle(bundle.getString("ReplaceDialog.title")); // NOI18N
		setResizable(false);

		jLblFind.setDisplayedMnemonic('F');
		jLblFind.setLabelFor(jCmbFind);
		jLblFind.setText(bundle.getString("ReplaceDialog.jLblFind.text")); // NOI18N

		jBtnNext.setIcon(new ImageIcon(FindAndReplaceDialog.class.getResource("/com/echeloneditor/resources/images/go-next.png"))); // NOI18N
		jBtnNext.setMnemonic('N');
		jBtnNext.setText(bundle.getString("ReplaceDialog.jBtnNext.text")); // NOI18N
		jBtnNext.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				// jBtnNextActionPerformed(evt);
			}
		});

		jBtnPrev.setIcon(new ImageIcon(FindAndReplaceDialog.class.getResource("/com/echeloneditor/resources/images/go-previous.png"))); // NOI18N
		jBtnPrev.setMnemonic('N');
		jBtnPrev.setText(bundle.getString("ReplaceDialog.jBtnPrev.text")); // NOI18N
		jBtnPrev.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				// jBtnPrevActionPerformed(evt);
			}
		});

		jBtnReplaceAll.setIcon(new ImageIcon(FindAndReplaceDialog.class.getResource("/com/echeloneditor/resources/images/edit-find-replace-all.png"))); // NOI18N
		jBtnReplaceAll.setMnemonic('H');
		jBtnReplaceAll.setText(bundle.getString("ReplaceDialog.jBtnReplaceAll.text")); // NOI18N
		jBtnReplaceAll.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				// jBtnReplaceAllActionPerformed(evt);
			}
		});

		jChkWrap.setMnemonic('W');
		jChkWrap.setText(bundle.getString("ReplaceDialog.jChkWrap.text")); // NOI18N
		jChkWrap.setToolTipText(bundle.getString("ReplaceDialog.jChkWrap.toolTipText")); // NOI18N

		jChkRegex.setMnemonic('R');
		jChkRegex.setText(bundle.getString("ReplaceDialog.jChkRegex.text")); // NOI18N

		jChkIgnoreCase.setMnemonic('I');
		jChkIgnoreCase.setText(bundle.getString("ReplaceDialog.jChkIgnoreCase.text")); // NOI18N

		jLblReplace.setDisplayedMnemonic('R');
		jLblReplace.setLabelFor(jCmbReplace);
		jLblReplace.setText(bundle.getString("ReplaceDialog.jLblReplace.text")); // NOI18N

		jTglHighlight.setIcon(new ImageIcon(FindAndReplaceDialog.class.getResource("/com/echeloneditor/resources/images/highlight.png"))); // NOI18N
		jTglHighlight.setText(bundle.getString("ReplaceDialog.jTglHighlight.text")); // NOI18N
		jTglHighlight.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				// jTglHighlightActionPerformed(evt);
			}
		});

		jCmbReplace.setEditable(true);

		jCmbFind.setEditable(true);

		jBtnReplace.setIcon(new ImageIcon(FindAndReplaceDialog.class.getResource("/com/echeloneditor/resources/images/edit-find-replace.png"))); // NOI18N
		jBtnReplace.setText(bundle.getString("ReplaceDialog.jBtnReplace.text")); // NOI18N
		jBtnReplace.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				// jBtnReplaceActionPerformed(evt);
			}
		});

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
				GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING).addComponent(jLblFind).addComponent(jLblReplace)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jCmbFind, 0, 289, Short.MAX_VALUE).addComponent(jCmbReplace, GroupLayout.Alignment.TRAILING, 0, 289, Short.MAX_VALUE).addComponent(jChkRegex, GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE).addComponent(jChkWrap, GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE).addComponent(jChkIgnoreCase, GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jBtnReplace, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE).addComponent(jBtnNext, GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE).addComponent(jBtnPrev, GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE).addComponent(jTglHighlight, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE).addComponent(jBtnReplaceAll, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(jLblFind).addComponent(jCmbFind, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE).addComponent(jBtnNext)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(jBtnPrev).addComponent(jCmbReplace, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE).addComponent(jLblReplace)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(jBtnReplace).addComponent(jChkWrap, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)).addGap(3, 3, 3).addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(jChkRegex).addComponent(jBtnReplaceAll)).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(jChkIgnoreCase).addComponent(jTglHighlight)).addContainerGap()));

		pack();
	}

	@Override
	public void caretUpdate(CaretEvent e) {
		// updateHighlights();
	}

	@Override
	public void escapePressed() {
		setVisible(false);
	}
}
